import adsk.core, adsk.fusion, adsk.cam, traceback
import math

bd = 0.7
sdy = 1.2
sdx = 0.6
ypiv1 = -1.2
ypiv2 = 1.3
draft = 3
depth = 1
deadrise = False #False when deadrise is zero, True otherwise
lb = 4
lm = 5
ls = 3
bs = 2
bwl = 5
topy_dis_1 = 1.3
topy_dis_2 = 0.9
toppd = 0.5 # pivot distance
frontpd = 1.2 # pivot distance
lwl = lb + lm + ls

def run(context):
    ui = None
    try: 
        app = adsk.core.Application.get()
        ui = app.userInterface
        doc = app.documents.add(adsk.core.DocumentTypes.FusionDesignDocumentType)
        design = app.activeProduct
        components = design.rootComponent.occurrences
        component = components.addNewComponent( adsk.core.Matrix3D.create( ) ).component
        
        sketch = component.sketches.add( component.xYConstructionPlane )
        
        def add_point(x,y,z, points): 
            points.add(adsk.core.Point3D.create(x, y, z))

        # curve 1
        points1=  adsk.core.ObjectCollection.create()
        x = lb/2
        y = topy_dis_1  
        add_point(0,0,draft,points1)
        add_point(x,y, draft, points1)
        add_point(lb-toppd, bwl/2, draft, points1)
        add_point(lb, bwl*1/2, draft, points1)
        sketch.sketchCurves.sketchFittedSplines.add(points1)

        # curve 2 
        points2 = adsk.core.ObjectCollection.create()
        add_point(lb, bwl*1/2, draft, points2)
        add_point(lb + lm, bwl*1/2, draft, points2)
        sketch.sketchCurves.sketchFittedSplines.add(points2)

        # curve 3
        x = (lb+lm + lb+lm+ls)/2
        y = bs/2 + topy_dis_2
        points3 = adsk.core.ObjectCollection.create()
        add_point(lb + lm, bwl*1/2, draft, points3)
        add_point(lb+lm, +toppd, bwl/2, draft, points3)
        add_point(x,y,draft, points3)
        add_point(lb+lm+ls, bs/2, draft,points3)
        sketch.sketchCurves.sketchFittedSplines.add(points3)

        # curve 4
        if bs!= 0: 
            points4 = adsk.core.ObjectCollection.create()
            add_point(lb+lm+ls, bs/2, draft, points4)
            add_point(lb+lm+ls, 0, draft)
            sketch.sketchCurves.sketchFittedSplines.add(points4)
    except:
        if ui:
            ui.messageBox('Failed:\n{}'.format(traceback.format_exc()))

